GET  http://localhost:3000/products?page=2&size=2
Content-Type: application/json
Accept: application/json

###
GET  http://localhost:3000/products/20
Content-Type: application/json
Accept: application/json

###
GET http://localhost:3000/products/filters?name=ka
Content-Type: application/json
Accept: application/json
